#%RAML 1.0 DataType
type: object
properties:
  recordAssessmentRequest:
    type: object
    properties:
      userDetails:
        type: object
        properties:
          userId:
            type: string
            required: true
            example: "REG1001"
          name:
            type: string
            required: true
            example:  "Kumar"
      assessmentdetails:
        type: array
        items:
          properties:
            question:
              type: string
              required: true
              example: "What Is an Investment Objective"
            answer:
              type: string
              required: true
              example: "Option1"
      submitionDateTime:
        type: string
        required: true
        example: "01-03-2022T12:20:30"