#%RAML 1.0 Trait
headers:
  x-fms-transactionId:
    type: string
    required: true
    minLength: 36
    maxLength: 36
    example: "123456789123456789123456789123456789"
  x-fms-clientId:
    type: string
    required: true
    example: "hsdfgysdhfcdshf37er6twgsdhfjcd"
  x-fms-clientSecret:
    type: string
    required: true
    example: "dsgfhaegur457r6ewsewegrfjesh"