#%RAML 1.0
title: assesment-sapi-raml
description: This Raml is for the assesment sapi API
version: 1.0.0
protocols:
  - HTTP
  - HTTPS

uses:
  common-library: /exchange_modules/7c07f543-6d00-433f-947f-08f2736c27c4/common-fragments-investment/1.0.22/common-fragments-investment.raml

types:
  Get-assessment-Report-Response: !include /dataType/get-assessment-report-response-dataType.raml

/assessments:
  description: This resources is used for assessment to check fund eligibality and submit fund eligibality assessments.
  get:
    description: This API will retrieve set of questions answer from salesforce system.
    is:
      - common-library.common-Header
      - common-library.common-error-reaponses
    
    responses:
      200:
        body:
          application/json:
            type: common-library.get-assessments-response
            example: !include examples/get-assessments-response-example-api.json
  post:
    description: This API will Record set of questions answer to salesforce system.
    is:
      - common-library.common-Header
      - common-library.common-error-reaponses
    body:
      application/json:
        type: common-library.post-assesssments-request
        example: !include examples/post-assessments-request-example-api.json
    responses:
      201:
        body:
          application/json:
            type: common-library.post-assesssments-response
            example: !include examples/post-assessments-response-example-api.json
  /report:
    /{customerId}:
      get:
        description: This API will generate report of assessment for user.
        is:
          - common-library.common-Header
          - common-library.common-error-reaponses
        responses:
          200:
            body:
              application/json:
                type: Get-assessment-Report-Response
                example: !include examples/Get-assessment-Report-Response-api.json
              
          

          


        
    

    


                  
                  



                  
            
                                          
                    
            
      

          
